export const product = [
  {
    id: 1,
    title: "Samsung Galaxy Book",
    brand: "samsung",
    price: 1350,
    category: "laptops",
    back: "green",
    stick: "_30_.svg",
    src: "laptops/samsung.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "Samsung Exynos",
    rate: 4
  },

  {
    id: 2,
    title: "MacBook Air M2",
    brand: "apple",
    price: 1500,
    category: "laptops",
    stick: "st1.svg",
    src: "laptops/macbook2air.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:0
  },
  {
    id: 8,
    title: "IPHONE 14 PRO MAX",
    brand: "apple",
    price: 1300,
    category: "phones",
    back: "green",
    stick: "_30_.svg",
    src: "phones/apple/i14PMBlack.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 256,
    camera: 13,
    processor: "MediaTek MT6739",
    rate: 4
  },
  {
    id: 6,
    title: "Apple Watch 5",
    brand: "apple",
    price: 200,
    category: "watches",
    src: "watchs/iWatch.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    stick: "st1.svg",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 8,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:3
  },
  {
    id: 3,
    title: "MacBook Pro 16",
    brand: "apple",
    price: 2000,
    category: "laptops",
    src: "laptops/macbook-pro.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    back: "green",
    stick: "_30_.svg",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:4
  },
  {
    id: 7,
    title: "Apple Watch 5",
    brand: "apple",
    price: 200,
    category: "watches",
    back: "green",
    stick: "_30_.svg",
    src: "watchs/iWatchBlack.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 4,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:4
  },
  {
    id: 4,
    title: "Acer Aspire 3",
    brand: "acer",
    price: 1000,
    category: "laptops",
    stick: "st1.svg",
    src: "laptops/acer-aspire3.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "Spreadtrum",
    rate:5
  },
  {
    id: 9,
    title: "IPHONE 14 PRO MAX",
    brand: "apple",
    price: 1300,
    category: "phones",
    back: "green",
    stick: "_30_.svg",
    src: "phones/apple/i14ProMaxGold.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 128,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:3
  },
  {
    id: 5,
    title: "HP Pavilion 15",
    brand: "huawei",
    price: 1200,
    category: "laptops",
    stick: "st1.svg",
    src: "laptops/hpp15.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/iPhone.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:4
  },
  {
    id: 10,
    title: "Samsung Galaxy Book",
    brand: "samsung",
    price: 1350,
    category: "laptops",
    back: "green",
    stick: "_30_.svg",
    src: "laptops/samsung.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 256,
    camera: 13,
    processor: "Samsung Exynos",
    rate:5
  },

  {
    id: 11,
    title: "MacBook Air M2",
    brand: "apple",
    price: 1500,
    back: "red",
    category: "laptops",
    stick: "td.svg",
    src: "laptops/macbook2air.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 256,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:5
  },
  {
    id: 12,
    title: "IPHONE 14 PRO MAX",
    brand: "apple",
    price: 1300,
    category: "phones",
    back: "green",
    stick: "_30_.svg",
    src: "phones/apple/i14PMBlack.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 128,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:3
  },
  {
    id: 13,
    title: "Apple Watch 5",
    brand: "apple",
    price: 200,
    category: "watches",
    src: "watchs/iWatch.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    stick: "st1.svg",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 4,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:2
  },
  {
    id: 14,
    title: "MacBook Pro 16",
    brand: "apple",
    price: 2000,
    category: "laptops",
    src: "laptops/macbook-pro.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    back: "red",
    stick: "td.svg",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:5
  },
  {
    id: 15,
    title: "Apple Watch 5",
    brand: "apple",
    price: 200,
    category: "watches",
    back: "green",
    stick: "_30_.svg",
    src: "watchs/iWatchBlack.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 8,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:1
    
  },
  {
    id: 16,
    title: "Acer Aspire 3",
    brand: "acer",
    price: 1000,
    category: "laptops",
    stick: "st1.svg",
    src: "laptops/acer-aspire3.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 18.5,
    razreshenie: "1600x720",
    localStorage: 512,
    camera: 13,
    processor: "Qualcomm Snapdragon",
    rate:3
  },
  {
    id: 17,
    title: "IPHONE 14 PRO MAX",
    brand: "apple",
    price: 1300,
    category: "phones",
    back: "green",
    stick: "_30_.svg",
    src: "phones/apple/i14ProMaxGold.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 64,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:4
  },
  {
    id: 18,
    title: "HP Pavilion 15",
    brand: "huawei",
    price: 1200,
    category: "laptops",
    back: "red",
    stick: "td.svg",
    src: "laptops/hpp15.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/iPhone.png",
    display: 16.5,
    razreshenie: "1600x720",
    localStorage: 256,
    camera: 13,
    processor: "Qualcomm Snapdragon",
    rate:4
  },
  {
    id: 19,
    title: "IPHONE 14 PRO MAX",
    brand: "apple",
    price: 1300,
    category: "phones",
    back: "red",
    stick: "td.svg",
    src: "phones/apple/i14PMBlack.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    display: 6,
    razreshenie: "1600x720",
    localStorage: 64,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:5
  },
  {
    id: 20,
    title: "Apple Watch 5",
    brand: "huawei",
    price: 200,
    category: "accessories",
    src: "watchs/iWatch.png",
    desc: "Lorem ipsum dolor mit",
    src2: "phones/apple/i14ProMaxGold.png",
    stick: "st1.svg",
    display: 6.5,
    razreshenie: "1600x720",
    localStorage: 32,
    camera: 13,
    processor: "MediaTek MT6739",
    rate:3
  }
]